## LUV experiment

In [7]:
import torch
from kornia import color
from torch.autograd import Variable

x = torch.tensor([[[30]],
                 [[40]],
                 [[40.]]])
x = Variable(torch.FloatTensor(x), requires_grad=True)

#x = torch.max(x, torch.tensor([[[1]],[[0]],[[0]]]) * 3.1)

print(x)

#l = color.rgb_to_luv(x)

#print(x)

x2 = color.luv_to_rgb(x)

c = torch.clamp(x2, 0., 1.)

print("rgb")
print(x2)

c.backward(torch.ones(c.shape))

print(x.grad)

tensor([[[30.]],

        [[40.]],

        [[40.]]], requires_grad=True)
rgb
tensor([[[ 0.4206]],

        [[ 0.2350]],

        [[-0.2304]]], grad_fn=<StackBackward>)
tensor([[[nan]],

        [[nan]],

        [[nan]]])


## LAB Experiment

In [10]:
import torch
from torch.autograd import Variable
from kornia_lab import RgbToLab, LabToRgb

r2l = RgbToLab()
l2r = LabToRgb()

x = torch.tensor([[[5]],
                 [[40]],
                 [[40.]]])
x = Variable(torch.FloatTensor(x), requires_grad=True)

#x = torch.max(x, torch.tensor([[[1]],[[0]],[[0]]]) * 3.1)

print(x)

#l = color.rgb_to_luv(x)
#print(x)

x2 = l2r.lab_to_rgb(x)

#c = torch.clamp(x2, 0., 1.)
c=x2

print("rgb")
print(x2)

c.backward(torch.ones(c.shape))

print(x.grad)


tensor([[[ 5.]],

        [[40.]],

        [[40.]]], requires_grad=True)
rgb
tensor([[[2.6528e-01]],

        [[1.2865e-10]],

        [[1.2865e-10]]], grad_fn=<SliceBackward>)
tensor([[[0.0073]],

        [[0.0029]],

        [[0.0008]]])
